version: '3'
services:
  apache:
    build: docker/apache
    container_name: my-php-container
    ports:
      - "8000:80"
    working_dir: /var/www/html
    volumes:
      - ./src/mantis:/var/www/html

  mysql:
    image: mariadb:latest
    links:
      - apache:mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bugtracker
      - MYSQL_USER=mantisbt
      - MYSQL_PASSWORD=mantisbt
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: nazarpc/phpmyadmin
    links:
      - mysql
    ports:
      - "5000:80"

  maildev:
    image: djfarrelly/maildev
    ports:
      - "1080:80"
      - "1025:25"

  portainer:
    image: portainer/portainer
    container_name: "portainer-app"
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  grafana:
    image: grafana/grafana
    container_name: "grafana-app"
    restart: always
    ports:
      - 3000:3000
    volumes:
      - grafana-volume:/var/lib/grafana

volumes:
  app-volume:
  grafana-volume:
